### ISSUE TITLE
Bug: NIST research area tags do not wrap when the page width is smaller than the length of the tag list

### ISSUE THREAD

**Issue by mkdjr** [usnistgov/oar-pdr#352]
Below` is a screenshot of my dataset's landing page. I've noted the issue with a red outline.
![Screenshot 2024-11-20 102719](https://github.com/user-attachments/assets/a50f90ca-7046-4d35-9ceb-32a454176226)

**Comment by RayPlante** [comment]
Thanks!  This fix is in and will go out in the next release.
